BookStore/Areas/Admin/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.BLL;
using BookStore.Models;
using BookStore.Helpers;

namespace BookStore.Areas.Admin.Controllers
{
    [Authorize]
    [ExceptionLogInfo]
    public class OrderController : Controller
    {
        private OrderManager om = new OrderManager();

        //显示全部订单信息
        public ActionResult Index(int pageIndex = 1)
        {
            int pageSize = 5;
            var orders = om.GetOrdersAll();
            decimal totalMoneys = 0;//所有订单总额
            foreach (var o in orders)
            {
                totalMoneys += o.TotalPrice;
            }
            ViewBag.TotalMoneys = totalMoneys;
            var pagedOrders = new PagedList<Order>(orders, pageSize, pageIndex);
            return View(pagedOrders);
        }
        //删除一个详情订单
        public ActionResult DeleteOrderDetail(int id)
        {
            try
            {
                new OrderDetailManager().DeleteById(id);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                string message = "数据库在执行删除详细订单操作时，出现异常。";
                Exception ex = new Exception(message);
                new ExceptionLogInfoAttribute().OnException(new ExceptionContext(this.ControllerContext, ex));
                return View("Error", new HandleErrorInfo(ex, @"Admin\Order", "DeleteOrderDetail"));
            }
        }

        //删除一个订单
        public ActionResult DeleteOrder(int id)
        {
            try
            {
                om.Delete(id);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                string message = "数据库在执行删除订单操作时，出现异常。";
                Exception ex = new Exception(message);
                new ExceptionLogInfoAttribute().OnException(new ExceptionContext(this.ControllerContext, ex));
                return View("Error", new HandleErrorInfo(ex, @"Admin\Order", "DeleteOrder"));
            }
        }
        //清空所有订单
        public ActionResult EmptyOrderAll()
        {
            try
            {
                om.EmptyAll();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                string message = "数据库在执行清空所有的订单操作时，出现异常。";
                Exception ex = new Exception(message);
                new ExceptionLogInfoAttribute().OnException(new ExceptionContext(this.ControllerContext, ex));
                return View("Error", new HandleErrorInfo(ex, @"Admin\Order", "EmptyOrderAll"));
            }
        }
    }
}

BookStore/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.Models;
using BookStore.BLL;
using BookStore.Helpers;

namespace BookStore.Controllers
{
    [ExceptionLogInfo]
    [VisitNoteLogInfo]
    public class BookController : Controller
    {
        private BookManager bm = new BookManager();

        //书籍详情页面
        [HandleError(Order=1,ExceptionType=typeof(Exception),View="Error")]//错误特性
        [OutputCache(Order=2,Duration = 3600)]//页面缓存（Duration：缓存时间[秒]）
        public ActionResult Detail(int id)
        {
            //int id = Convert.ToInt32(RouteData.Values["Id"]);
            Book book = bm.GetBookById(id);
            //ViewBag.Book = book;
            return View(book);
        }
        //分页显示分类图书
        public ActionResult List(int categoryId, string sort = "PublishDate DESC", int pageIndex=1)
        {
            //设置页面标题
            Categorie category = new CategoryManager().GetCategorieById(categoryId);
            ViewBag.Title = category != null ? category.Name + "_分类图书列表_第三波书店" : "分类图书列表_第三波书店";//类别名称
            //分页图书
            if (pageIndex < 1)
            {
                pageIndex = 1;
            }
            int pageSize = 5;
            string condition = "And CategoryId="+categoryId;
            int recordCount;
            var books = bm.GetBooks(pageSize,pageIndex,condition,sort,out recordCount);
            int totalPages = recordCount % pageSize == 0 ? recordCount / pageSize : recordCount / pageSize + 1;
            if (totalPages==0)
            {
                totalPages = 1;
            }
            if (pageIndex>totalPages)
            {
                pageIndex = totalPages;
                books = bm.GetBooks(pageSize, pageIndex, condition, sort, out recordCount);
            }
            ViewBag.TotalPages = totalPages;
            ViewBag.PageIndex = pageIndex;
            ViewBag.Sort = sort;
            ViewBag.CategoryId = categoryId;
            return View(books);
        }
        //搜索图书页面 + 自定义分页
        public ActionResult Search(string title,int? category,int pageIndex = 1)
        {
            //获取全部类别，并绑定到下拉列表
            ViewBag.category = new SelectList(new CategoryManager().GetCategoriesAll(),"Id","Name");
            string condition = string.Empty;
            string cateTitle = "";
            //拼接条件
            if (category.HasValue)
            {
                condition += string.Format(" And CategoryId={0}",category);
                //获取图书分类对象,分类名称
                Categorie tempCategory = new CategoryManager().GetCategorieById(category.Value);
                if (tempCategory != null)
                {
                    cateTitle = tempCategory.Name+"_";
                }
            }
            if (!string.IsNullOrEmpty(title) && title.Trim()!="")
            {
                condition += string.Format(" And Title Like'%{0}%'",title);
                //添加搜索词
                new SearchKeywordManager().Add(title);
            }
            condition += " Order By Clicks Desc";
            //设置页面标题
            ViewBag.Title = !string.IsNullOrEmpty(title) ? cateTitle + title + "_图书搜索页_第三波书店" : cateTitle + "图书搜索页_第三波书店";
            //根据条件获得图书集合
            var books = bm.GetBooks(condition);
            int pageSize = 10;
            //如果是post请求，则说明是通过条件查询图书，pageIndex=1
            if (Request.RequestType == "POST")
            {
                pageIndex = 1;
            }
            if (pageIndex < 1)
            {
                pageIndex = 1;
            }
            //分页
            var pagedBooks = new PagedList<Book>(books,pageSize,pageIndex);
            return View(pagedBooks);
        }
    }
}

BookStore/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@using BookStore.Models;
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width" />
    <meta name="author" content="Hz"/>
    <meta name="description" content="第三波网上书店"/>
    <meta name="keywords" content="第三波，第三波网上书店,图书，Java，C#,ASP.NET,软件开发，编程图书,管理员"/>
    <title>@ViewBag.Title</title>
	<link href="~/Areas/Admin/Content/Admin.css" rel="stylesheet" />
    <link href="~/Content/themes/base/minified/jquery-ui.min.css" rel="stylesheet" />
    <script type="text/javascript" src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery-ui-1.8.20.min.js"></script>
    <script type="text/javascript" src="~/Scripts/Public.js"></script>
	@RenderSection("scripts", required: false)
	@RenderSection("styles",required:false)
</head>
<body>
	 <div id="container">
        <div id="head">
            <img alt="" src="~/Areas/Admin/Images/admin_top.gif" />
        </div>
        <div id="main">
            <div id="nav">
                <div id="navTop">
                    <strong>
                        @if(Session["User"]!=null){
                            @((Session["User"] as UserInfo).Name)
                        }
                        else
                        {
                            <text>管理员</text>
                        }
                       ，您好
                    </strong>
                    <hr />
                </div>
                <div id="navMiddle">
                    <ul>
                        <li>@Html.ActionLink("订单管理","Index","Order")</li>
                        <li>@Html.ActionLink("用户管理","Index","User")</li>
                        <li>@Html.ActionLink("用户状态管理","Index","UserState")</li>
                        <li>@Html.ActionLink("图书分类管理","Index","Category")</li>
                        <li>@Html.ActionLink("图书管理","Index","Book")</li>
                        <li>@Html.ActionLink("出版社管理","Index","Publisher")</li>
                        <li>@Html.ActionLink("安全退出","CheckOut","Account")</li>
                    </ul>
                </div>
                <div id="navBottom"></div>
            </div>
            <div id="content">
            	@RenderBody()
            </div>
        </div>
    </div>
</body>
</html>